name: Veracode Test
on: [push, pull_request]

jobs:
  Build:
    name: Maeven build
    runs-on: self-hosted
    container:
      image: maven:3.9.6-eclipse-temurin-17
      options: --user root
    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Maeven build
        run: |
          mvn package -DskipTests
          ls -l
      - name: Upload artfacts
        uses: actions/upload-artifact@v3
        with:
          name: artfacts
          path: .